services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pleiades_dev_db 
    ports:
      - '5432:5432' 
    expose:
      - '5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d pleiades_dev_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-db: 